### ISSUE TITLE
Http module not found

### ISSUE THREAD

**Issue by legop3** [Piripe/BDPlugins#2]
### Plugin

DCController

### Plugin Version

0.0.3

### Install Source

Official Better Discord plugins list/Plugin Repo

### Expected Behavior vs Actual Behavior

plugin does not load, hasnt for a while

### Steps to reproduce - Ensure to include actual links!

1. install plugin
2. load discord (from closed)

### Other details

`Error: ENOENT: no such file or directory, lstat 'C:\Users\minec\AppData\Local\Discord\app-1.0.9007\http'
    at Object.T [as realpathSync] (<anonymous>:4:346490)
    at Function.getFilePath (<anonymous>:4:347760)
    at Function._load (<anonymous>:4:347855)
    at <anonymous>:4:351046
    at plugin (betterdiscord://plugins/DCController.plugin.js:60:18)
    at eval (betterdiscord://plugins/DCController.plugin.js:497:16)
    at eval (betterdiscord://plugins/DCController.plugin.js:498:7)
    at eval (betterdiscord://plugins/DCController.plugin.js:499:3)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)`
    
error output

**Comment by Piripe** [comment]
Yeah, it's an already known issues, I already tried to update the plugin 2 times but the http module (The module that allows the plugin to open a web server in Discord) is no longer available.

I'll take a look another time today and I'll ask if I can access to the http module on the BD Discord server.

**Comment by Piripe** [comment]
Sorry, this plugin is no longer possible. If BD reimplement a way to open a web server you can mention me and I'll update the plugin.
